---
development:
  url: {{envOr "DEVELOPMENT_DATABASE_URL" "mysql://goshorter:goshorter@(localhost:3306)/goshorter_development?parseTime=true&multiStatements=true&readTimeout=3s&collation=utf8mb4_general_ci"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/goshorter_test?parseTime=true&multiStatements=true&readTimeout=3s&collation=utf8mb4_general_ci"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/goshorter_production?parseTime=true&multiStatements=true&readTimeout=3s&collation=utf8mb4_general_ci"}}
