package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"github.com/magikid/goshorter/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ShortenedLink)
// DB Table: Plural (shortened_links)
// Resource: Plural (ShortenedLinks)
// Path: Plural (/shortened_links)
// View Template Folder: Plural (/templates/shortened_links/)

// ShortenedLinksResource is the resource for the ShortenedLink model
type ShortenedLinksResource struct {
	buffalo.Resource
}

// List gets all ShortenedLinks. This function is mapped to the path
// GET /shortened_links
func (v ShortenedLinksResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	shortenedLinks := &models.ShortenedLinks{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all ShortenedLinks from the DB
	if err := q.All(shortenedLinks); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("shortenedLinks", shortenedLinks)
		return c.Render(http.StatusOK, r.HTML("shortened_links/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(shortenedLinks))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(shortenedLinks))
	}).Respond(c)
}

// Show gets the data for one ShortenedLink. This function is mapped to
// the path GET /shortened_links/{shortened_link_id}
func (v ShortenedLinksResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ShortenedLink
	shortenedLink := &models.ShortenedLink{}

	// To find the ShortenedLink the parameter shortened_link_id is used.
	if err := tx.Find(shortenedLink, c.Param("shortened_link_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("shortenedLink", shortenedLink)

		return c.Render(http.StatusOK, r.HTML("shortened_links/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(shortenedLink))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(shortenedLink))
	}).Respond(c)
}

// New renders the form for creating a new ShortenedLink.
// This function is mapped to the path GET /shortened_links/new
func (v ShortenedLinksResource) New(c buffalo.Context) error {
	c.Set("shortenedLink", &models.ShortenedLink{})

	return c.Render(http.StatusOK, r.HTML("shortened_links/new.plush.html"))
}

// Create adds a ShortenedLink to the DB. This function is mapped to the
// path POST /shortened_links
func (v ShortenedLinksResource) Create(c buffalo.Context) error {
	// Allocate an empty ShortenedLink
	shortenedLink := &models.ShortenedLink{}

	// Bind shortenedLink to the html form elements
	if err := c.Bind(shortenedLink); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(shortenedLink)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("shortenedLink", shortenedLink)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("shortened_links/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "shortenedLink.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/shortened_links/%v", shortenedLink.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(shortenedLink))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(shortenedLink))
	}).Respond(c)
}

// Edit renders a edit form for a ShortenedLink. This function is
// mapped to the path GET /shortened_links/{shortened_link_id}/edit
func (v ShortenedLinksResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ShortenedLink
	shortenedLink := &models.ShortenedLink{}

	if err := tx.Find(shortenedLink, c.Param("shortened_link_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("shortenedLink", shortenedLink)
	return c.Render(http.StatusOK, r.HTML("shortened_links/edit.plush.html"))
}

// Update changes a ShortenedLink in the DB. This function is mapped to
// the path PUT /shortened_links/{shortened_link_id}
func (v ShortenedLinksResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ShortenedLink
	shortenedLink := &models.ShortenedLink{}

	if err := tx.Find(shortenedLink, c.Param("shortened_link_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind ShortenedLink to the html form elements
	if err := c.Bind(shortenedLink); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(shortenedLink)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("shortenedLink", shortenedLink)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("shortened_links/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "shortenedLink.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/shortened_links/%v", shortenedLink.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(shortenedLink))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(shortenedLink))
	}).Respond(c)
}

// Destroy deletes a ShortenedLink from the DB. This function is mapped
// to the path DELETE /shortened_links/{shortened_link_id}
func (v ShortenedLinksResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ShortenedLink
	shortenedLink := &models.ShortenedLink{}

	// To find the ShortenedLink the parameter shortened_link_id is used.
	if err := tx.Find(shortenedLink, c.Param("shortened_link_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(shortenedLink); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "shortenedLink.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/shortened_links")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(shortenedLink))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(shortenedLink))
	}).Respond(c)
}

// Show gets the data for one ShortenedLink. This function is mapped to
// the path GET /shortened_links/{shortened_link_id}
func RedirectHandler(c buffalo.Context) error {
	// Get the DB connection from the context
	_, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ShortenedLink
	shortenedLink := &models.ShortenedLink{}

	err := models.DB.Where("short_code = ?", c.Param("shortCode")).First(shortenedLink)

	if err != nil {
		return c.Error(http.StatusNotFound, err)
	}
	c.Logger().Infof("Redirecting to %v", shortenedLink.URL)
	return c.Redirect(http.StatusTemporaryRedirect, shortenedLink.URL)
}
