on:
  push:
    # We want to run the workflow on all branches.
    # But you can restrict the runs if necessary.
    branches:
      - "*"
    tags:
      - "*"
  repository_dispatch:
    types: manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.7"

      - uses: actions/checkout@v3

      - name: Vars
        id: vars
        run: |
          echo "::set-output name=version_tag::${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=go_cache::$(go env GOCACHE)"

      - name: Cache the build cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.vars.outputs.go_cache }}
          key: ${{ runner.os }}-go1.17.7-release-${{ hashFiles('**/go.sum') }}
          restore-keys: |
                        ${{ runner.os }}-go1.17.7-release

      - run: mkdir -p public/assets
      - run: go install github.com/gobuffalo/cli/cmd/buffalo@v0.18.3
      - run: go mod download
      - run: yarn install
      - name: Build release package
        run: buffalo build --verbose --clean-assets --static --environment production
        if: startsWith(github.ref, 'refs/tags/')
      - name: Create github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
          prerelease: true
