on:
  push:
    # We want to run the workflow on all branches.
    # But you can restrict the runs if necessary.
    branches:
      - "*"
    tags:
      - "*"
  repository_dispatch:
    types: manual

jobs:
  ci:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go: ["1.16.x", "1.17.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1.7.0
        id: gofaster
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          key: ${{runner.os}}-go${{matrix.go}}-${{ hashFiles('**/go.sum') }}
          path: |
            ${{steps.gofaster.outputs.GOCACHE}}
            ${{steps.gofaster.outputs.GOMODCACHE}}
      - run: 'go install github.com/gobuffalo/cli/cmd/buffalo@v0.18.3'
      - run: 'go mod download'
      - run: 'yarn install'
      - run: 'go vet ./...'
      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}
      - name: Build release package
        run: 'mkdir -p public/assets && buffalo build --verbose --clean-assets --static --environment production'
        if: startsWith(github.ref, 'refs/tags/')
      - name: Create github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
